=== NoCodeMonkey/ryanleeder.me/config/skills-schema.json
{
  "$id": "http://ryanleeder.me/config.json",
  "type": "array",
  "definitions": {},
  "$schema": "http://json-schema.org/draft-06/schema#",
  "items": {
    "$id": "http://ryanleeder.me/config.json/items",
    "type": "object",
    "properties": {
      "name": {
        "$id": "http://ryanleeder.me/config.json/items/properties/name",
        "type": "string",
        "title": "The Name Schema ",
        "default": "",
        "examples": [
          "Front-End Web Development Skills"
        ]
      },
      "abbreviation": {
        "$id": "http://ryanleeder.me/config.json/items/properties/abbreviation",
        "type": "string",
        "title": "The Abbreviation Schema ",
        "default": "",
        "examples": [
          "Front-End"
        ]
      },
      "icon": {
        "$id": "http://ryanleeder.me/config.json/items/properties/icon",
        "type": "string",
        "title": "The Icon Schema ",
        "default": "",
        "examples": [
          "fas fa-code"
        ]
      },
      "skills": {
        "$id": "http://ryanleeder.me/config.json/items/properties/skills",
        "type": "array",
        "items": {
          "$id": "http://ryanleeder.me/config.json/items/properties/skills/items",
          "type": "object",
          "properties": {
            "name": {
              "$id": "http://ryanleeder.me/config.json/items/properties/skills/items/properties/name",
              "type": "string",
              "title": "The Name Schema ",
              "default": "",
              "examples": [
                "HTML / HTML5"
              ]
            },
            "competency": {
              "$id": "http://ryanleeder.me/config.json/items/properties/skills/items/properties/competency",
              "type": "integer",
              "title": "The Competency Schema ",
              "default": 0,
              "examples": [
                95
              ]
            },
            "description": {
              "$id": "http://ryanleeder.me/config.json/items/properties/skills/items/properties/description",
              "type": "string",
              "title": "The Description Schema ",
              "default": "",
              "examples": [
                "This is a long description. "
              ]
            }
          },
          "required": ["name","competency","description"],
          "additionalProperties" : false
        }
      }
    },
    "required": ["name", "abbreviation", "icon"]
  }
}

=== NoCodeMonkey/ryanleeder.me/config/skills.json
[
  {
    "name": "Front-End Web Development Skills",
    "abbreviation": "Front-End",
    "icon": "fas fa-code",
    "skills": [
      {
        "name": "HTML / HTML5",
        "competency": 95,
        "description": ""
      },
      {
        "name": "CSS / CCS3",
        "competency": 90,
        "description": ""
      },
      {
        "name": "JavaScript / jQuery",
        "competency": 95,
        "description": ""
      },
      {
        "name": "CSS Frameworks",
        "competency": 90,
        "description": "Bootstrap, foundation etc."
      },
      {
        "name": "Javascript Frameworks",
        "competency": 65,
        "description": ""
      },
      {
        "name": "Responsive Web Design",
        "competency": 90,
        "description": ""
      },
      {
        "name": "Mobile Web Development",
        "competency": 85,
        "description": ""
      },
      {
        "name": "Progressive Enhancement / Graceful Degradation",
        "competency": 82,
        "description": ""
      },
      {
        "name": "Cross-Browser / Cross-Platform Development",
        "competency": 92,
        "description": ""
      },
      {
        "name": "Feature Detection",
        "competency": 78,
        "description": "Feature Queries (@supports), Modernizr etc."
      },
      {
        "name": "UX / Usability",
        "competency": 84,
        "description": ""
      },
      {
        "name": "Website Speed / Performance",
        "competency": 80,
        "description": ""
      },
      {
        "name": "Developer/Debugging Tools",
        "competency": 94,
        "description": "Chrome Dev Tools, Fiddler, Firebug etc."
      },
      {
        "name": "CSS Pre-Processors",
        "competency": 82,
        "description": "Sass, Less, Stylus etc."
      },
      {
        "name": "CSS Post-Processors",
        "competency": 73,
        "description": "Autoprefixer, PostCSS etc."
      },
      {
        "name": "JavaScript Transpilers",
        "competency": 66,
        "description": "TypeScript, CoffeeScript, BabelJS etc."
      },
      {
        "name": "JavaScript Versions",
        "competency": 64,
        "description": "ECMAScript 6, ES.Next etc."
      },
      {
        "name": "Module/Dependency Loaders",
        "competency": 68,
        "description": "Webpack, Browserify, RequireJS etc."
      },
      {
        "name": "JavaScript Test Frameworks",
        "competency": 72,
        "description": "Mocha, Jasmine, QUnit etc."
      },
      {
        "name": "Linters & Code Quality Tools",
        "competency": 75,
        "description": "ESLint, JSLint, JSHint, Stylelint etc."
      },
      {
        "name": "SVG",
        "competency": 65,
        "description": "Scalable vector graphic design and implementation."
      }
    ]
  },
  {
    "name": "Back-End Development Skills",
    "abbreviation": "Back-End",
    "icon": "fas fa-cogs",
    "skills": [
      {
        "name": ".NET Framework",
        "competency": 95,
        "description": "Server-side applications implemented in .NET Framework."
      },
      {
        "name": ".NET Core",
        "competency": 90,
        "description": "Server-side applications implemented in .NET Core."
      },
      {
        "name": "ASP.NET Web Forms",
        "competency": 95,
        "description": ""
      },
      {
        "name": "ASP.NET MVC",
        "competency": 90,
        "description": ""
      },
      {
        "name": "ASP.NET Web API",
        "competency": 88,
        "description": ""
      },
      {
        "name": "Node.js",
        "competency": 85,
        "description": "Server-side development on Node.js."
      },
      {
        "name": "LINQ",
        "competency": 85,
        "description": "Language Integrated Query."
      },
      {
        "name": "Redis",
        "competency": 87,
        "description": "Redis back-end storage/caching."
      },
      {
        "name": "Entity Framework",
        "competency": 85,
        "description": "Object-relational mapping using entity framework."
      },
      {
        "name": "NHibernate",
        "competency": 80,
        "description": "Object-relational mapping using NHibernate."
      },
      {
        "name": "SignalR",
        "competency": 80,
        "description": "Server-to-client remote procedure calls using SignalR."
      },
      {
        "name": "Socket.IO",
        "competency": 75,
        "description": "Bi-directional remote procedure calls using Socket.IO."
      },
      {
        "name": "Web Services",
        "competency": 95,
        "description": "Design, implementation, and Data integration using web services."
      },
      {
        "name": "ASP.NET Identity/IdentityServer",
        "competency": 75,
        "description": "Authentication and authorization."
      },
      {
        "name": "SQL Server",
        "competency": 95,
        "description": "Back-end development using SQL Server."
      },
      {
        "name": "MySQL",
        "competency": 80,
        "description": "Back-end development using MySQL."
      },
      {
        "name": "MongoDB",
        "competency": 70,
        "description": "Back-end development using MongoDB."
      },
      {
        "name": "SQLite",
        "competency": 85,
        "description": "Back-end development using SQLite."
      },
      {
        "name": "SQLite",
        "competency": 85,
        "description": "Back-end development using SQLite."
      }
    ]
  },
  {
    "name": "Business Skills",
    "abbreviation": "Business",
    "icon": "fas fa-user-tie",
    "skills": [
      {
        "name": "Business Process Analysis & Modelling",
        "competency": 89,
        "description": "Interpret and understand the requirements of the company's customer base to develop appropriate business requirements and technical specifications."
      },
      {
        "name": "Delivering To Defined Timelines",
        "competency": 90,
        "description": "Working with developers and testers and work within project timelines and budgets to meet business requirements."
      },
      {
        "name": "Project Management Frameworks",
        "competency": 84,
        "description": "Agile to Scrum to Waterfall to Kanban etc."
      },
      {
        "name": "Work Estimation & Planning",
        "competency": 78,
        "description": "Estimate the resources, budget, time and risks and then formulate a project plan and schedule."
      },
      {
        "name": "Company Standards & Guidelines",
        "competency": 95,
        "description": "To develop software according to published standards and guidelines, including code standards and user interface design guidelines."
      },
      {
        "name": "Understanding Of Change Management",
        "competency": 78,
        "description": "Ensure that changes are recorded and then evaluated, authorized, prioritized, planned, tested, implemented, documented and reviewed by participating and provide input on go/no-go decisions for product releases."
      },
      {
        "name": "Technical Writing",
        "competency": 80,
        "description": "Write documentation for projects, including requirements, the architecture/design document, code documentation, test plans and test cases, and end-user documentation."
      },
      {
        "name": "Testing, Fault Location & Rootcause Analysis",
        "competency": 90,
        "description": "Supporting and resolving product issues alongside test and quality assurance teams."
      },
      {
        "name": "Maintaining & Improving Existing Applications",
        "competency": 95,
        "description": "Maintain an excellent level of understanding and knowledge of company's products, processes and services to research, test, and coordinates the conversion and/or integration of new features based on client requirements."
      },
      {
        "name": "Code & Architecture Reviews",
        "competency": 86,
        "description": "Reviews software architectural decisions with respect to their impact on performance as well as other quality attributes, such as reliability or modifiability and examine source code to find mistakes, thereby improving overall code quality."
      },
      {
        "name": "Mentor & Coaching",
        "competency": 78,
        "description": "Provide technical guidance and educate team members and coworkers on policies, practices and process to collaboratively & efficiently."
      },
      {
        "name": "Software Development Trends",
        "competency": 75,
        "description": "Maintaining a strong understanding of software development trends and technology."
      },
      {
        "name": "Continuous Integration and Deployment",
        "competency": 70,
        "description": "Jenkins, Bitbucket, Maven, JIRA etc."
      }
    ]
  },
  {
    "name": "General Skills",
    "abbreviation": "General",
    "icon": "fas fa-user-check",
    "skills": [
      {
        "name": "Time Management",
        "competency": 89,
        "description": "Able to multitask, prioritize, and manage time efficiently."
      },
      {
        "name": "Communications & Negotiation Skills",
        "competency": 85,
        "description": "Communicate clearly to both technical and business people at all levels."
      },
      {
        "name": "Innovation",
        "competency": 96,
        "description": "The ability to come up with new ideas and techniques."
      },
      {
        "name": "Source Control",
        "competency": 92,
        "description": "Working with multiple source controls: Git, CVS, VSS, SVN etc."
      },
      {
        "name": "Automation and Task Runners",
        "competency": 84,
        "description": "Workflow management tools: Grunt, Gulp, Webpack etc."
      },
      {
        "name": "Package Managers",
        "competency": 90,
        "description": "npm, Bower etc."
      },
      {
